@baseUrl = http://localhost:3017
@id = post-1

### Check the API
GET {{baseUrl}}/

### Read likes for an id
GET {{baseUrl}}/like/{{id}}

### Add one like for an id
POST {{baseUrl}}/like/{{id}}

### Read likes again
GET {{baseUrl}}/like/{{id}}
