services:
  mongodb:
    image: mongo:7
    container_name: io-system-design-03-mongodb
    ports:
      - "27031:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_03_data:/data/db

volumes:
  mongodb_03_data:
